# Generated by Django 3.0 on 2020-12-18 06:49

from django.db import migrations, models
import home_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('duration_hours', models.IntegerField(null=True)),
                ('course_price', models.IntegerField(null=True)),
                ('unique_number', models.IntegerField(default=home_page.models.random_number)),
            ],
        ),
    ]
